version: '3.5'

services:
  # Products service - spring boot and oracle
  products-db:
    container_name: products-db
    image: gvenzl/oracle-xe
    ports:
      - "11521:1521"
    environment:
      - ORACLE_PASSWORD=password
      - ORACLE_DATABASE=products
      - APP_USER=products
      - APP_USER_PASSWORD=password
  products-app:
    container_name: products-app
    image: products-app
    build:
      context: ./products
    ports:
      - "18081:8080"
      - "18001:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # Cart service - spring boot and postgres
  cart-db:
    container_name: cart-db
    image: postgres
    ports:
      - "15433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cart
    extra_hosts:
      - "host.docker.internal:host-gateway"
  cart-app:
    container_name: cart-app
    image: cart-app
    build:
      context: ./cart
    ports:
      - "18082:8080"
      - "18002:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # Payment service - spring boot and postgres
  payment-db:
    container_name: payment-db
    image: postgres
    ports:
      - "15434:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=payment
    extra_hosts:
      - "host.docker.internal:host-gateway"
  payment-app:
    container_name: payment-app
    image: payment-app
    build:
      context: ./payment
    ports:
      - "18083:8080"
      - "18003:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # Stats service
  stats-app:
    container_name: stats-app
    image: stats-app
    build:
      context: ./stats
    ports:
      - "18084:8080"
      - "18004:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"